import React, { useEffect } from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { useLanguage } from '../context/LanguageContext';

export default function TermsOfUse() {
  const { lang, t } = useLanguage();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <Navbar />
      <div className="w-full min-h-screen bg-background pt-32 pb-16 px-8 flex justify-center">
        <div className="w-full max-w-4xl flex flex-col gap-8 text-ghost">
          <h1 className="font-sans font-bold text-4xl md:text-5xl tracking-tight text-accent mb-4">
            {t('termsOfUse')}
          </h1>
          
          {lang === 'tr' ? (
            <div className="font-mono text-sm md:text-base text-ghost/70 flex flex-col gap-6 leading-relaxed">
              <p>Son Güncelleme: {new Date().toLocaleDateString('tr-TR')}</p>
              
              <section>
                <h2 className="font-sans font-bold text-xl text-ghost mb-3">1. Kabul Edilme Şartları</h2>
                <p>Bu web sitesine erişerek ve hizmetlerimizi kullanarak, bu Kullanım Koşulları'nı okuduğunuzu, anladığınızı ve kabul ettiğinizi beyan edersiniz. Koşulları kabul etmiyorsanız lütfen siteyi kullanmayınız.</p>
              </section>

              <section>
                <h2 className="font-sans font-bold text-xl text-ghost mb-3">2. Yapay Zeka Çözümleri ve Karar Destek Bildirimi</h2>
                <p>Tarafımızca geliştirilen yapay zeka ajanları, otomasyonlar ve analitik araçlar <strong>karar destek sistemleri</strong> olarak tasarlanmıştır. Bu sistemlerin ürettiği çıktılar, tahminler veya otomatik yanıtlar nihai ve kesin iş kararları yerine geçmez. Üretilen içerik veya yapılan işlemlerden doğabilecek doğrudan veya dolaylı maddi/manevi zararlardan ajansımız (Tahir Kemal Sarıyıldız) sorumlu tutulamaz. İnsan denetimi (human-in-the-loop) her zaman tavsiye edilir.</p>
              </section>

              <section>
                <h2 className="font-sans font-bold text-xl text-ghost mb-3">3. Fikri Mülkiyet Hakları</h2>
                <p>Sitede yer alan metinler, görseller, kodlar, tasarımlar ve konseptler aksi belirtilmedikçe Tahir Kemal Sarıyıldız'a aittir. Önceden yazılı izin alınmaksızın kopyalanamaz, çoğaltılamaz veya ticari amaçla kullanılamaz. Müşteriler için geliştirilen özel yazılımların mülkiyet hakları, ilgili sözleşmelerde ayrıca belirlenir.</p>
              </section>

              <section>
                <h2 className="font-sans font-bold text-xl text-ghost mb-3">4. Sorumluluk Sınırlandırması</h2>
                <p>Hizmetlerimizin kesintisiz veya hatasız olacağını garanti etmiyoruz. Siber saldırılar, üçüncü taraf API kesintileri (örn. OpenAI çökmeleri) veya mücbir sebeplerden kaynaklanan veri kayıpları veya hizmet aksamaları konusunda dolaylı sorumluluğumuz bulunmamaktadır.</p>
              </section>
            </div>
          ) : (
            <div className="font-mono text-sm md:text-base text-ghost/70 flex flex-col gap-6 leading-relaxed">
              <p>Last Updated: {new Date().toLocaleDateString('en-US')}</p>
              
              <section>
                <h2 className="font-sans font-bold text-xl text-ghost mb-3">1. Acceptance of Terms</h2>
                <p>By accessing this website and using our services, you declare that you have read, understood, and agreed to these Terms of Use. If you do not agree with the terms, please do not use the site.</p>
              </section>

              <section>
                <h2 className="font-sans font-bold text-xl text-ghost mb-3">2. AI Solutions & Decision Support Notice</h2>
                <p>The AI agents, automations, and analytical tools developed by us are designed as <strong>decision support systems</strong>. Outputs, predictions, or automated responses generated by these systems do not replace final and definitive business decisions. Our agency (Tahir Kemal Sarıyıldız) cannot be held liable for any direct or indirect material/moral damages arising from the generated content or executed actions. Human oversight (human-in-the-loop) is always highly recommended.</p>
              </section>

              <section>
                <h2 className="font-sans font-bold text-xl text-ghost mb-3">3. Intellectual Property Rights</h2>
                <p>Unless otherwise stated, all texts, images, codes, designs, and concepts on this site belong to Tahir Kemal Sarıyıldız. They cannot be copied, reproduced, or used for commercial purposes without prior written permission. Property rights for custom software developed for clients are specified separately in their respective contracts.</p>
              </section>

              <section>
                <h2 className="font-sans font-bold text-xl text-ghost mb-3">4. Limitation of Liability</h2>
                <p>We do not guarantee that our services will be uninterrupted or error-free. We bear no indirect liability for data losses or service disruptions caused by cyber attacks, third-party API outages (e.g., OpenAI downtimes), or force majeure events.</p>
              </section>
            </div>
          )}
        </div>
      </div>
      <Footer />
    </>
  );
}
